public class Dogs {
    public String name;
    public String breed;
    public integer age;

    public void description(){

        // aşağıdakini yaptı ama hata verdi neden yaptı anlamadım.
        // string desc = 'Age of ' + Name;
        system.debug('Age of ' + name + 'is ,' + Age + ', and its breed is ' + breed + '.');
    }
    // bunu yaptı ama neden yaptı bilemedim.
    // public void dummyMethod(){
    //     system.debug(desc);
    }
}