conditionClassAssignment m = new conditionClassAssignment();

String outputMonth1 = m.ifClassMethod(1);
system.debug('outputMonth1 is ' + outputMonth1);

String outputMonth12 = m.ifClassMethod(12);
system.debug('outputMonth12 is ' + outputMonth12);

string quarter1 = m.caseMethod('January');
system.debug('quarter1 is ' + quarter1);

string quarter2 = m.caseMethod('December');
system.debug('quarter4 is ' + quarter1);