string index2Candidate = ListDemo5.candidateList(2);
system.debug('index2Candidate = ' + index2Candidate);

string index5candidate = ListDemo5.candidateList(5);
system.debug('index 5 candidate = ' + index5candidate);

string indexminus5candidate = listDemo5.candidateList(-5);
system.debug(indexminus5candidate);
string index0candidate = ListDemo5.candidateList(0);
system.debug(index0candidate);

ListDemo5.randomIntegerList();
ListDemo5.allCats();